### ISSUE TITLE
 The Minimal Superpermutation of Haruhi Suzumiya

### ISSUE THREAD

**Issue by milesgould-continuum** [TOTES-Edinburgh/TOTES-Edinburgh.github.io#11]
## Talk Topic

 The Minimal Superpermutation of Haruhi Suzumiya

## Talk Description
In 2014, amateur mathematician Robin Houston used open-source tools to find a counterexample to the 20-year-old "minimal superpermutation conjecture". Soon after, he learned that the best known bound on the length of superpermutations was to be found in a 4chan post about the anime _The Melancholy of Haruhi Suzumiya_. This led to an open and ongoing collaboration between amateurs and professionals to find tighter bounds, in the best traditions of citizen science. Though the problem itself is easy to understand, it connects to deep areas of mathematics; I'll give a quick overview of the history of the problem, progress since 2014, and how you can help.

## Talk Audience Level

Novice

**Comment by milesgould-continuum** [comment]
On length: it is definitely possible to explain the problem and describe how Houston found his counterexample in the space of a lightning talk, because Houston did exactly that at the 2014 MathsJam Gathering :-) I think it would be possible to cut that down enough to leave space for subsequent progress (he also talked about the related notion of De Bruijn sequences, which I could cut). On the other hand, it might be a bit of a firehose for the audience - I'd need to do some rehearsals to check.

**Comment by milesgould-continuum** [comment]
https://docs.google.com/presentation/d/15gpgc5ebrcr3q7VJM5idDPOcRhMTOHph0b0DX0vWwUY/edit?usp=sharing

**Comment by taikedz** [comment]
Delivered, 20th of April
