### ISSUE TITLE
Using Python to read home smart meter data

### ISSUE THREAD

**Issue by taikedz** [TOTES-Edinburgh/TOTES-Edinburgh.github.io#12]
## Talk Topic

Martin Jones : Personal Python prject

## Talk Description

Using Python to read smart electricity/gas meter data

## Talk Audience Level

Novice

**Comment by mojones** [comment]
[martin_jones_smart_meter_data_20.04.2022.pdf](https://github.com/TOTES-Edinburgh/TOTES-Edinburgh.github.io/files/8522942/martin_jones_smart_meter_data_20.04.2022.pdf)

**Comment by taikedz** [comment]
Delivered, 20th of April
