### ISSUE TITLE
Career and Modding in Minetest

### ISSUE THREAD

**Issue by taikedz** [TOTES-Edinburgh/TOTES-Edinburgh.github.io#13]
## Talk Topic

Career and Modding in Minetest 

## Talk Description

What does piddling around with game modding in Lua have to do with a career in DevOps and development? Quite a bit actually, when you take an open source approach...

## Talk Audience Level

Novice

**Comment by taikedzierski-ldx** [comment]
Slides from talk: [minetest-and-career.pdf](https://github.com/TOTES-Edinburgh/TOTES-Edinburgh.github.io/files/8532221/minetest-and-career.pdf)

**Comment by taikedz** [comment]
Slides from talk: [minetest-and-career.pdf](https://github.com/TOTES-Edinburgh/TOTES-Edinburgh.github.io/files/8532685/minetest-and-career.pdf)

**Comment by taikedz** [comment]
Delivered, 20th of April
