### ISSUE TITLE
Get Started Building GUIs using Fyne

### ISSUE THREAD

**Issue by andydotxyz** [TOTES-Edinburgh/TOTES-Edinburgh.github.io#14]
## Talk Topic

Getting started building your first cross-platform native app using Go and Fyne.

## Talk Description

An overview of how easily anyone can start building gui apps with Go and Fyne. From hello world to App Store distribution in a few short steps. Covering app layout, widgets, data access and more. Plus a quick overview of powerful advanced features too.

## Talk Audience Level

Novice

**Comment by taikedz** [comment]
Hi @andydotxyz - thanks for your talk offer :-)

Would you want to do this as a lightning talk (5-10 minutes?) or a full talk? (20-45min) ?

Next event for lightning talks would be in June ; next session for a full-length talk in May, or in August (the latter providing we can book Codebase given that it could be festival period).

**Comment by andydotxyz** [comment]
Sorry, I didn't think to add as I was asked to add this to fill a lightning spot this week.
I guess that is now filled so I can offer either.
I can cover the content above in 7 minutes, or do an expanded version with more details at around 30 - 40 mins.

**Comment by taikedz** [comment]
@andydotxyz Second full-talk at the May event would be superb if you would be up for it ?

**Comment by andydotxyz** [comment]
I guess having jumped in and presented lightning version last week this may be done.

If there is a future desire to have a longer version with code and tool demos I'd be happy - but don't want to re-visit the podium too fast :).

**Comment by taikedz** [comment]
Thanks very much @andydotxyz for jumping in last-second last week ! Verycool stuff :D 

Marking as delivered 👍
