### ISSUE TITLE
Building workflows on k8s using argo workflows 

### ISSUE THREAD

**Issue by thatGreekGuy96** [TOTES-Edinburgh/TOTES-Edinburgh.github.io#6]
## Talk Topic
Lightning talk: showing off a really cool framework that sits on top of kubernetes and allows you to define cloud workflows in yaml files. 
...

## Talk Description

* Quick overview of argo workflows 
* Cool examples 
* Pros and cons 
...

## Talk Audience Level

Enthusiast

**Comment by taikedz** [comment]
Delivered March 2022
