### ISSUE TITLE
Woodland Opportunity Map Wales 2021

### ISSUE THREAD

**Issue by anthonyrandell** [TOTES-Edinburgh/TOTES-Edinburgh.github.io#7]
## Open data to support tree planting in Wales 

...

## Talk Description

This was a project to source, review and create open data sets for understanding constraints affecting tree planting, and for creating raster scoring layers to rank where to plant trees based on Welsh Gov't policy objectives. 

https://datamap.gov.wales/maps/woodland-opportunity-map-2021/

The data sets were then styled and shared on a platform using a number of open software products including geoserver, postgres, geonode, mapstore2.

## Talk Audience Level

Enthusiast

**Comment by thatGreekGuy96** [comment]
Hey Anthony, thanks for the offer to give a talk! Just wanting to confirm that you are still up for it, this Wednesday at around 7pm? 

The event starts at 630 but since it is the "inaugural" event we are wanting to give an intro talk first.

**Comment by anthonyrandell** [comment]
Hi, yes all good to go.

Wednesday at 7pm is fine. I might need to faff with the technology a bit.
Hoping to show the data using my laptop.

Cheers,
Anthony

**Comment by taikedz** [comment]
Delivered March 2022
